spring:
  thymeleaf:
    enabled: false
  profile: local
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    initialization-mode: always
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    #      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false # property to avoid clob warning
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect # property to avoid clob warning


#BASE DE DATOS LOCAL
#spring:
#  thymeleaf:
#    enabled: false
#  profile: local
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/tfg?useSSL=false
#    username: root
#    password: ubuntuserver
#    initialization-mode: always
#  jackson:
#    serialization:
#      WRITE_DATES_AS_TIMESTAMPS: false
#    time-zone: UTC
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create-drop
#    #      ddl-auto: update
#    properties:
#      hibernate:
#        temp:
#          use_jdbc_metadata_defaults: false # property to avoid clob warning
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect # property to avoid clob warning
#
#
